### ISSUE TITLE
Redirection vers les mentions légales depuis la version EN

### ISSUE THREAD

**Issue by DirtyF** [WeLoveSpeed/welovespeed.com#16]
### Comportement constaté

Si je visite la page https://www.welovespeed.com/en/
Quand je clique sur le lien  'Legal informations (fr)' du pied de page (https://www.welovespeed.com/en/legal-mentions/)
Alors je suis redirigé vers https://welovespeed.com//mentions-legales/ 
Et j'ai une erreur 443 : connexion refusée

### Comportement attendu

Je suis correctement redirigé vers la page des mentions légales

@welovespeed/staff

**Comment by borisschapira** [comment]
Merci Frank !
