### ISSUE TITLE
EN version: French in the EN version

### ISSUE THREAD

**Issue by borisschapira** [WeLoveSpeed/welovespeed.com#176]
### Observation

Some talks titles & descriptions on https://www.welovespeed.com/en/2024/speakers/ are in French

### Expectation

All talks titles and descriptions are in English.

@welovespeed/staff

**Comment by borisschapira** [comment]
Is someone working on this or do you want me to propose a PR?

**Comment by borisschapira** [comment]
What fix?

**Comment by JulienPradet** [comment]
@borisschapira  Sorry about the miscommunication. Should be truly fixed now.

I was away on holidays and failed the initial publish. :/ Thanks for noticing!
