### ISSUE TITLE
Il ne faudrait pas une majuscule pour le bouton sur la home ?

### ISSUE THREAD

**Issue by Nazcange** [WeLoveSpeed/welovespeed.com#29]
https://github.com/WeLoveSpeed/welovespeed.com/blob/7c3a4fcc9529c9fb2a1fe101938e421901fb5d2b/_data/translations.yml#L69

**Comment by borisschapira** [comment]
En fait, c'est minuscule sur les autres boutons, donc j'ai homogénéisé, merci.

Fixed by 6ee39c94376c0d98252eb63610d91b8968361f48
