### ISSUE TITLE
Repasser sur le site 2020 pour supprimer les traces d'une édition présentielle

### ISSUE THREAD

**Issue by borisschapira** [WeLoveSpeed/welovespeed.com#70]
### Comportement constaté

Sur certaines pages, dont au moins https://www.welovespeed.com/2020/billetterie/, on parle de l'événement présentiel, avec heure d'arrivée et de fin, collations et repas.

### Comportement attendu

Les pages devraient parler de l'événement en ligne.

@welovespeed/staff

**Comment by jpvincent** [comment]
Merci d'avoir veillé au grain je pense que la billetterie était le seul endroit qui faisait référence à du présentiel, j'ai fixé la page FR et EN (pas encore déployé)
